version: '3'

services:
  # Database
  db:
    image: mariadb
    volumes:
      - ./.docker/databases:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - wpsite
  # Database manager
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - wpsite
  # Wordpress
  wordpress:
    depends_on:
      - db
    build: ./.docker/${WP_VERSION}
    ports:
      - '8000:80'
    restart: always
    volumes:
      - ${SITE_PATH}:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_enable=1
      PHP_EXTENSION_XDEBUG: 1
    networks:
      - wpsite

networks:
  wpsite:
